### ISSUE TITLE
Home page overscroll

### ISSUE THREAD

**Issue by Trickygamers** [Wolfyxon/3ds-web-stuff#16]
When I scroll down then quickly back up with my finger/stylus the app/txt will scroll beyond the intended distance.
Also I managed to get around my schools restrictions so now I can share screenshots and maybe videos so heres a image of what I see.
![image](https://github.com/Wolfyxon/3ds-web-stuff/assets/86691033/c856e622-a4fb-44c7-b240-4f5392d60b92)

**Comment by Wolfyxon** [comment]
I think it's the browser's fault and I don't think I can do much about that.
Also since it doesn't really break anything I'll leave it.

**Comment by Trickygamers** [comment]
> I think it's the browser's fault and I don't think I can do much about that. Also since it doesn't really break anything I'll leave it.

Could you at least make it snap back in place?

**Comment by Wolfyxon** [comment]
Alright I'll see
