### ISSUE TITLE
[SUGGESTION]3d gun game

### ISSUE THREAD

**Issue by Trickygamers** [Wolfyxon/3ds-web-stuff#3]
A 3d shooting game where the goal is to kill all the enemys and go to the exit. With all kinds of illusions, tricks, puzzles, and trolls to hold the player back. The controls would be D-pad up/down to move back and forth, 
D-pad left/right to move the camera, a to shoot, and to changing wepons and open doors use the touch screen.

**Comment by Wolfyxon** [comment]
First I have to make a 3D rendering library or find something that works on the 3DS.
I'll probably make it at some point.

**Comment by Wolfyxon** [comment]
I'll close it for now since it's something to do in far future.
