### ISSUE TITLE
[Question] Fullscreen api

### ISSUE THREAD

**Issue by Trikkii** [Wolfyxon/3ds-web-stuff#36]
I was looking at what the browser can do and I saw that fullscreen functionality is doable and was wondering what it would look like when in use and what it does.

**Comment by Wolfyxon** [comment]
Nintendo's website states that the browser has Fullscreen API, but I tried using it multiple times with no effect.
Calling any function from the fullscreen API causes errors and setting properties (the old way) has no effect.

**Comment by Trikkii** [comment]
So I guess this is something to figure out later on or hope someone els figures it out.

**Comment by Wolfyxon** [comment]
Yep. Assuming it's actually true
