### ISSUE TITLE
[Jetfighter] pop-up error

### ISSUE THREAD

**Issue by Trikkii** [Wolfyxon/3ds-web-stuff#38]
I was checking out the new update and got this pop-up: https://Wolfyxon.github.io/3ds-web-stuff/games/jetfighter/jetfighter.js:173 NOT_FOUND_ERR: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist. But when I tapped continue the came continued as normal. Also the game thinks I am tapping the a button every frame.

**Comment by Wolfyxon** [comment]
I added a check if the projectile exists before removing it.
Should work fine now.

> Also the game thinks I am tapping the a button every frame.

This was caused by the error popup
