### ISSUE TITLE
[SUGGESTION] Physics playground

### ISSUE THREAD

**Issue by Trickygamers** [Wolfyxon/3ds-web-stuff#5]
It is what the title says things like sand, water, fire, lava, ragdolls, guns,  bombs, changing of gravity/time, and more are simulated interacting with one another.

**Comment by Wolfyxon** [comment]
This is wonderful, but I probably wouldn't be able to do that as it involves a lot of physics calculations. Also performance might be terrible.

I'll consider making this in future, closing for now.

**Comment by Trickygamers** [comment]
Ok I understand.
