### ISSUE TITLE
[Calculator] numbers go off screen and - goes below off screen

### ISSUE THREAD

**Issue by Trickiy** [Wolfyxon/3ds-web-stuff#67]
![image](https://github.com/Wolfyxon/3ds-web-stuff/assets/86691033/989c29d6-be67-4bbe-983b-686f1b5edabf)

**Comment by Wolfyxon** [comment]
I'll re-design the upper screen actually.

**Comment by Wolfyxon** [comment]
Here's how it looks now
![image](https://github.com/Wolfyxon/3ds-web-stuff/assets/58263600/67a4dc70-624a-4335-b221-fe369175ab1d)

**Comment by Trickiy** [comment]
ooooh

**Comment by Trickiy** [comment]
The numbers still go off screen.
![image](https://github.com/Wolfyxon/3ds-web-stuff/assets/86691033/7bbda69e-98de-4ec1-8d4f-317c22962582)
